config/routes.rb
Ministrandi::Application.routes.draw do
  
  namespace :feedstocks do
    get :print_inventory
    get :list_critic_stock

    resources :outputs do
      resource :finish, controller: 'outputs/finish',  only: :update
      resources :items, controller: 'outputs/items'
    end
    
    resources :entrances do
      resource :finish, controller: 'entrances/finish',  only: :update
      resources :items, controller: 'entrances/items'
    end
  end
  
  resources :cashiers do
    resource :close, controller: 'cashiers/close', only: :update
    get :daily_sale_report, :on => :member
  end
  
  namespace :cashiers do
    resources :entrances
    resources :outs
    resources :sales do
      resource :finish, controller: 'sales/finish', only: :update
      resources :items, controller: 'sales/items'
    end
  end
  
  namespace :reports do
    resources :comissions,    only: :index
    resources :sales,         only: :index
    resources :stocks,        only: :index
    resources :stores_sales,  only: :index
    resources :clients,       only: :index
  end

  namespace :autocompletes do
    resources :search_postal_codes, only: :index
    resources :search_cities, only: :index
    resources :suppliers, only: :index
    resources :feedstocks, only: :index
    resources :vendors, only: :index
    resources :clients, only: :index
    resources :products, only: :index
    resources :stock_industries, only: :index
    resources :stock_stores, only: :index
    resources :addresses, only: :index
  end
  
  resources :clients

  resources :orders do
    resource :attendance, controller: 'orders/attendance',  only: :update
    resource :attending,  controller: 'orders/attending',   only: :update
    resource :ready,      controller: 'orders/ready',       only: :update
    resource :deliver,    controller: 'orders/deliver',     only: :update
    resource :cancel,     controller: 'orders/cancel',      only: :update
    
    get :print, :on => :member
    get :print_done, :on => :member
    get :attendances, :on => :collection
    get :list_delivers, :on => :collection
    
    resources :exchange_items, controller: 'orders/exchange_items', only: [:create, :destroy]

    resources :items, controller: 'orders/items' do
      get :attendances, :on => :collection
    end
  end
  
  resources :center_costs
  resources :suppliers
  resources :clients
  resources :addresses
  resources :search_suggestions
  resources :feedstocks
  resources :bills

  namespace :products do
    resources :groups
  end
  
  resources :products do
    get :print_industry_price, :on => :collection
    get :find_by_barcode, :on => :collection
  end

  resources :stocks do
    collection do
      get :store_list
      get :change
      get :level
    end
  end
  
  root :to => 'home#index'
  devise_for :users
end

app/models/bill.rb
class Bill < ActiveRecord::Base
  belongs_to :supplier

  attr_accessible :number, :description, :barcode, :state, :release, :payment_day, :category, :bank, :valor, :valor_paid, 
  				  :supplier_id, :center_cost_id,  :supplier, :feedstock_entrance_id

  state_machine initial: :payable do
    event :payment do
      transition :payable => :paid
    end
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
	before_filter :build_new, :only => [:new, :create]

	def index
		@bills = Bill.all
	end

	def create
		@bill.save
		respond_with @bill		
	end

	private
  def build_new
    @bill = Bill.new
    @bill = Bill.new(bill_params) if bill_params.present?
  end

   def bill_params
    params.require(:bill).permit(:number, :description, :barcode, :state, :release, 
    														 :payment_day, :category, :bank, :valor, :valor_paid, 
  				  										 :supplier_id, :center_cost_id, :feedstock_entrance_id) if params[:bill].present?
  end
end

app/views/bills/_form.html.erb
<%= simple_form_for @bill, :url => bills_path, :html => { :class => 'form-horizontal' }, wrapper: :horizontal_form do |f| %>
  <%= f.error_notification %>
  
  <div class="form-inputs">
    <%= f.input :category, :as => :select, :collection => Bills::Category.to_a, :selected => Bills::Category::BILLET %>

    <%= f.input :supplier, 
        as: :string, input_html: {  placeholder: "Pesquise o fornecedor", autofocus: true }, 
        required: true  %>
    <%= f.input :supplier_id, as: :hidden %>   
    <%= f.input :release, :as => :datetime_picker %>
    <%= f.input :payment_day, :as => :datetime_picker %>
    <%= f.input :number %> 
    <%= f.input :barcode %>
    
    <%= f.input :bank, :as => :select, :collection => Bills::Banks.to_a, :selected => Bills::Banks::BRASIL %>
    <%= f.input :valor %>
    <%= f.input :valor_paid %>
    <%= f.input :feedstock_entrance_id %>
    <%= f.input :description %>
    <%= f.input :center_cost_id, 
    :as => :select, 
    :collection => nested_options(CenterCost) %>   
     
  </div>

  <div class="form-actions">
    <%= f.button :submit, "Salvar Conta", :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                root_path, :class => 'btn' %>
  </div>
<% end %>

app/views/bills/index.html.erb
<div class="page-header">
  <h1>Contas a Pagar <%= link_to 'Nova', new_bill_path, :class => 'btn btn-primary' %></h1> 
</div>
<table class="table table-striped table-bordered table-condensed" id="clients_table">
  <thead>
    <tr>
      <th>Descrição</th>
      <th>Fornecedor</th>
      <th>Valor</th>
      <th>Data Vencimento</th>
      <th>Ações</th>
    </tr>
  </thead>

  <tbody>
    <% @bills.each do |bill| %>
      <tr>
        <td><%= bill.description %></td>
        <td><%= bill.supplier %></td>
        <td><%= bill.valor %></td>
        <td><%= bill.payment_day %></td>
        <td><%= link_to 'Editar', edit_bill_path(bill), :class => 'btn btn-sm btn-primary' %>
            <%= link_to 'Apagar', bill, 
            method: :delete, 
            data: { confirm: 'Tem certeza?' },
            :class => 'btn btn-sm btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>